name: Daily Screenshot

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run script
        run: python script.py

      - name: Upload artifacts (PNG + PDF)
        uses: actions/upload-artifact@v4
        with:
          name: hurricanezone-${{ github.run_id }}
          path: |
            output/**/hurricanezone_full.png
            output/**/hurricanezone_scroll.pdf
          if-no-files-found: error
          retention-days: 30

      # Opzionale: comprimi tutto in un singolo file per email (utile se >2 allegati)
      - name: Zip outputs (optional)
        run: |
          mkdir -p dist
          tar -czf dist/hurricanezone_${{ github.run_id }}.tar.gz -C output .

      - name: Send email with attachments
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          # Mittente e destinatari
          from: ${{ secrets.MAIL_FROM }}
          to: ${{ secrets.MAIL_TO }}
          subject: "Daily HurricaneZone – run ${{ github.run_id }} ({{date}})"
          # Corpo (HTML consentito)
          content_type: text/html
          body: |
            <p>Ciao,</p>
            <p>in allegato la cattura giornaliera di <b>https://www.hurricanezone.org/</b>.</p>
            <p>Puoi anche scaricare gli artifact qui:<br>
            <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">
              Run #${{ github.run_id }}
            </a></p>
            <p>— GitHub Actions</p>
          # Allegati: scegli UNA delle due opzioni qui sotto
          # 1) allega direttamente PNG e PDF (se sono piccoli)
          attachments: |
            output/**/hurricanezone_full.png
            output/**/hurricanezone_scroll.pdf
          # 2) OPPURE allega l'archivio compresso creato sopra (commenta le 2 righe di attachments e sblocca questa)
          # attachments: |
          #   dist/hurricanezone_${{ github.run_id }}.tar.gz
